In [2]:
import numpy as np
print("Numpy Imported")

Numpy Imported


In [3]:
lin_space = np.linspace([0,0,0], [10,20,30], 10 ,axis=1)
#lin_space -> make a np array (start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
#endpoint=True -> including the last origin(index:50) from the (num=50).
#retstep=False -> if you want to return only array, retstep=True -> return the steps also(lin_space,steps = np.linspace(0,5,num=50,retstep=True))
#dtype=None -> Type of the output values, Default: float64
#axis -> control the call index/column function
#and the shape organization rather insert as    axis=0 : (10, 3) ,     axis=1 : (3, 10)
l1 = lin_space[0]
l2 = lin_space[1]
l3 = lin_space[2]

print(f"l1:\n{l1}")
print(f"l2:\n{l2}")
print(f"l3:\n{l3}")
print(f"\nlin space:\n{lin_space.shape}")

l1:
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
l2:
[ 0.          2.22222222  4.44444444  6.66666667  8.88888889 11.11111111
 13.33333333 15.55555556 17.77777778 20.        ]
l3:
[ 0.          3.33333333  6.66666667 10.         13.33333333 16.66666667
 20.         23.33333333 26.66666667 30.        ]

lin space:
(3, 10)


In [12]:
ara_nge = np.arange(0, 10, 2,dtype=float)
#ara_nge -> make a np array ([start,] stop, [step,] dtype=None, *, like=None)
#start -> Default = 0
#step -> jump size between origins
#like -> return the new array as type as the input array(GPU,NumPy,CPU)

print(f"\narrange:\n{ara_nge}")


arrange:
[0. 2. 4. 6. 8.]


In [5]:
zeros_arr = np.zeros((2,),dtype=int,like=ara_nge)
ones_arr = np.ones((2,),dtype=int,like=ara_nge)
#zeros_arr -> make a np array od values=0 (shape, dtype, order='C'/'F', *, like=None)
#shape >= 1D writen with () as tuple if more then 1 Dimension.
print(f"\nzeros_arr:\n{zeros_arr}")
print(f"\nones_arr:\n{ones_arr}")


zeros_arr:
[0 0]

ones_arr:
[1 1]


In [6]:
full_arr = np.full((2,2),7)
# fill the entire new array/matrix with specific value. (shape, fill_value, dtype=None, order='C', *, like=None)
print(f"full_arr:\n{full_arr}")

full_arr:
[[7 7]
 [7 7]]


In [7]:
eye_arr = np.eye(N=4,M=5,k=1)
# fill the new matrix's slant with value = 1 and all other fields with value = 0 (N, M=None, k=0, dtype=float, order='C', *, like=None)
#N -> number of rows if N=4 matrix.shape = (4,4) #if you want to change the column count you add optional M=count (Default:None)
#k -> declare where the start point of the matrix's slant.(Optional,Default=None)
print(f"eye_arr:\n{eye_arr}")

eye_arr:
[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
random_arr = np.random.random(size=(2,2))
# always return [float]/matrix[float] unless size=None in this case the function return float.
print(f"random_arr:\n{random_arr}")

random_arr:
[[0.37983616 0.05820108]
 [0.01815644 0.00884212]]


In [9]:
empty_arr = np.empty(shape=(3,5))
#this function reusing the "garbage" values of the existing memory anf fill the new array/matrix with them.
# the values in this out-put is an accident because in the previous cell we declare arr of zeros, we can't
# start from an assumption that the values will be only 0. if you put shape=(20,20) probably the values won't be 0.
#       (shape, dtype=float, order='C', *, like=None)
print(f"empty_arr:\n{empty_arr}")


empty_arr:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
