In [13]:
import numpy as np
print("Imported")

Imported


In [14]:
a = np.array([
    [10,2,3,4]
    ,[5,6,7,8]
])

a.shape
#Array shape info: index 0 in (2,4) is indexes (2)
#                  index 1 in (2,4) is fields  (4)


(2, 4)

In [15]:
a =  np.array([1,2,3,4])
b = np.array([
    [10,2,3,4]
    ,[5,6,7,8]
])
print("a : \n",a)
print("len(a) = ",len(a))
print("b : \n",b)
print("len(b) = ",len(b))
#Length of array samples/indexes/rows


a : 
 [1 2 3 4]
len(a) =  4
b : 
 [[10  2  3  4]
 [ 5  6  7  8]]
len(b) =  2


In [16]:
b = np.array([
    [10,2,3,4]
    ,[5,6,7,8]
])
b.ndim
#Number of array dimensions


2

In [17]:
e = np.array([
    [10,2,3,4]
    ,[5,6,7,8]
])
e.size
#the len(function) but every single element in the given array.


8

In [18]:
b = np.array([
    [10,2,3,4]
    ,[5,6,7,8]
])
b.dtype
#Data type of array elements


dtype('int64')

In [19]:
b = np.array([
    [10,2,3,4]
    ,[5,6,7,8]
])
b.dtype.name
#Name of data type

'int64'

In [20]:
b = np.array([
    [10,2,3,4]
    ,[5,6,7,8]
])
b = b.astype(bool)
print("b.astype(bool):",b.dtype.name)

b = b.astype(float)
print("b.astype(float):",b.dtype.name)
# Convert an array to a different type


b.astype(bool): bool
b.astype(float): float64


In [21]:
# Help
np.info(np.ndarray.dtype)

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>
