In [1]:
import numpy as np

print("Imported")

Imported


In [2]:
a = np.array([ [1,2,3,4,5],
               [1,2,3,4,5] ])

mask = np.array([[True,True,False,True,True],
                 [True,True,True,True,True]])

sum_a = a.sum(axis=None, dtype=None, keepdims=False , initial=0, where=mask)
# Array-wise sum
# (axis=None, dtype=None, keepdims=False, initial=0, where=True)
# axis = None  -> Default, sum of all values in a, axis=0 -> sum of columns, axis=1 -> sum of indexes/rows.
# keepdims=False -> Default, change the shape of the output(according to axis), keepdims=True -> save the number dimension.
# initial=0 -> Default, the start number of the sum,(initial = 7 -> a.sum() + 7)
#  where=mask -> all True values mentioned in mask will count in np.sum(),
#  you can use 1D array for mask only if it's length equals to (a) length.
# if you want to be more specific you can define each cell from (a) with his own cell in mask.

print("a: ",a)
print("a.sum() =  ",sum_a)

a:  [[1 2 3 4 5]
 [1 2 3 4 5]]
a.sum() =   27


In [3]:
min_a = a.min(axis=None,initial=100)
# Array-wise minimum value
# ( axis=None, keepdims=False, initial=None, where=True)

print("a: ",a)
print("a.min() =  ",min_a)


a:  [[1 2 3 4 5]
 [1 2 3 4 5]]
a.min() =   1


In [4]:
max_a = a.max(axis=None,initial=0)
# Maximum value of an array row
#(axis=None, keepdims=False, initial=None, where=True)

print("a: ",a)
print("a.max() =  ",max_a)

a:  [[1 2 3 4 5]
 [1 2 3 4 5]]
a.max() =   5


In [5]:
cumsum_a = a.cumsum(axis=1)
# Cumulative sum of the elements
# (axis=None, dtype=None)
# calculate the sum of each element with all his pre cells.
print("a: ",a)
print("a.cumsum() =  ",cumsum_a)

a:  [[1 2 3 4 5]
 [1 2 3 4 5]]
a.cumsum() =   [[ 1  3  6 10 15]
 [ 1  3  6 10 15]]


In [6]:
mean_a = a.mean()
# Mean
# (axis=None, dtype=None, keepdims=False, where=True)

print("a: ",a)
print("a.mean() =  ",mean_a)

a:  [[1 2 3 4 5]
 [1 2 3 4 5]]
a.mean() =   3.0


In [7]:
c = np.array([7,2,3,4,5,6,1])
print("c before np.median() : ",c)

median_c = np.median(c,overwrite_input=True)
#Median
# (axis=None, overwrite_input=False, keepdims=False)
# overwrite_input=False -> Default, if you put True at value it is changing the original c
# sorting before definition of the median while True Saving place in the memory


print("c.median() =  ",median_c)
print("c after np.median(): ",c)

c before np.median() :  [7 2 3 4 5 6 1]
c.median() =   4.0
c after np.median():  [1 2 3 4 5 6 7]


In [23]:
g = np.array([1,2,3,4,5])
h = np.array([1,2,3,9,1])

t = np.array([[1,2,3,4,5],
              [6,7,8,9,10]])

g_corrcoef = np.corrcoef(g,h,rowvar=True)
t_corrcoef = np.corrcoef(t,rowvar=False)
#Correlation coefficient
# (x, y=None, rowvar=True, bias=False, ddof=None)
# rowvar=True -> Default, each *index\row* is variable, rowvar=False -> same but each *column*

# np.corrcoef(g,h) =
#   [[1.         0.33071891]
#   [0.33071891 1.        ]]
# each '1' value represent the variable with the same variable,
# index[0,1] and index[1,0] (0.33071891) represents the correlation's between both
# variables [0,1] in one order and [1,0] with the second order(example: gh | hg)
# this function helps on ML projects to prepare the data better, removing double features
# and corr that more strong from the defined threshold.

print("g: ",g)
print("h: ",h)
print("t: ",t)
print(f"np.corrcoef(t) = \n",t_corrcoef)
print(f"np.corrcoef(g,h) = \n",g_corrcoef)

g:  [1 2 3 4 5]
h:  [1 2 3 9 1]
t:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
np.corrcoef(t) = 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
np.corrcoef(g,h) = 
 [[1.         0.33071891]
 [0.33071891 1.        ]]


In [67]:
std_arr = np.array([[1,2,3,4,5],
                   [6,7,8,9,10]])

arr_std = np.std(std_arr)
#Standard deviation

print(f"std_arr:\n",std_arr)
print("public std: ",arr_std)

#avg = np.mean(std_arr)
#print("avg: ",avg)

avg_arr = np.sum(std_arr) / (std_arr.shape[1]*std_arr.shape[0])
print(f"1)  avg arr: ",avg_arr)

arr_minus_avg_powered = (std_arr-avg_arr)**2
print(f"2)  arr_minus_avg_powered:\n",arr_minus_avg_powered)

avg_arr_minus_avg_powered = (np.sum(arr_minus_avg_powered) / (arr_minus_avg_powered.shape[0]*arr_minus_avg_powered.shape[1]))
print(f"3)  avg arr_minus_avg_powered: ",avg_arr_minus_avg_powered)

std_locally = np.sqrt(avg_arr_minus_avg_powered)
print("4)   std locally: ",std_locally)

std_arr:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
public std:  2.8722813232690143
1)  avg arr:  5.5
2)  arr_minus_avg_powered:
 [[20.25 12.25  6.25  2.25  0.25]
 [ 0.25  2.25  6.25 12.25 20.25]]
3)  avg arr_minus_avg_powered:  8.25
4)   std locally:  2.8722813232690143


In [79]:
a = np.random.randint(0,10,(3,4))
print("a:\n",a)

sorted_a = np.sort(a,axis=-1)
# Sort Arrays
# NOT changing the original, sending a copy,
# a.sort() YES changing the original object but return nothing.
#  axis= 1/-1 -> Default, sort Indexes. axis= 0 -> sort Columns ,
# axis = None return new 1D Sorted array

# kind -> options: ['quicksort','mergesort','heapsort','stable']
# quicksort -> Default, very fast.  mergesort -> more stable with locations.
# heapsort -> less common.          stable -> keep the chronological order with equals values.
# order -> if you have a few features you can decide to sort specifics fields
print("sorted_a:\n",sorted_a)


#Sort an array

a:
 [[4 3 0 8]
 [4 7 8 3]
 [7 3 4 6]]
sorted_a:
 [0 3 3 3 4 4 4 6 7 7 8 8]


In [81]:
h = a.view()
# Create a view of the array with the same data
# Point to the same memory field you change the view object you changing the original memory field(h)
# unlike np.copy(a) it is sending a new memory field with a new data same as (a).

print("a: ",a)
print("a.view() =  ",h)

a:  [[4 3 0 8]
 [4 7 8 3]
 [7 3 4 6]]
a.view() =   [[4 3 0 8]
 [4 7 8 3]
 [7 3 4 6]]
