In [2]:
import numpy as np

print("Imported")

Imported


In [3]:
#   Subsetting
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
subsetting_1 = a[2]
#Select the element at the 2nd index 3

print("a: ",a)
print("a[2] =",subsetting_1)

a:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
a[2] = [7 8 9]


In [4]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
subsetting_2 = b[1,2]
#Select the element at row 1 column 2, 6.0 (equivalent to b[1][2])

print("b: ",b)
print("\nb[1,2] =",subsetting_2)


b:  [[1 2 3]
 [4 5 6]
 [7 8 9]]

b[1,2] = 6


In [5]:
#  Slicing
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
slicing_1 = a[0:2]
#Select items at index 0 and 1 array([1, 2])

print("a: ",a)
print("\na[0:2] =\n",slicing_1)

a:  [[1 2 3]
 [4 5 6]
 [7 8 9]]

a[0:2] =
 [[1 2 3]
 [4 5 6]]


In [6]:
slicing_2 = b[0:2,1]
#Select items at rows 0 and 1 in column 1 array([ 2., 5.])

print("b: ",b)
print("\nb[0:2],1 =\n",slicing_2)


b:  [[1 2 3]
 [4 5 6]
 [7 8 9]]

b[0:2],1 =
 [2 5]


In [7]:
slicing_3 = b[:1]
#Select all items at row 0 array([[1.5, 2., 3.]]) (equivalent to b[0:1, :])

print("b: ",b)
print("\nb[:1] =",slicing_3)

b:  [[1 2 3]
 [4 5 6]
 [7 8 9]]

b[:1] = [[1 2 3]]


In [8]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("c: ",c)

slicing_4 = c[0,...]
print("\nc[1,...] =\n",slicing_4)
#Same as [1,:,:]
# c[...,1] for fields(columns) , c[0,...] for rows(indexes)

dm = np.round(np.random.random((3,3,3)),0)
print("dm: ",dm)

dm_slice = dm[1,...]
print("dm_slice: ",dm_slice)


c:  [[1 2 3]
 [4 5 6]
 [7 8 9]]

c[1,...] =
 [1 2 3]
dm:  [[[0. 1. 1.]
  [1. 0. 0.]
  [0. 0. 1.]]

 [[1. 1. 1.]
  [0. 0. 1.]
  [1. 1. 0.]]

 [[1. 1. 0.]
  [0. 0. 1.]
  [1. 0. 1.]]]
dm_slice:  [[1. 1. 1.]
 [0. 0. 1.]
 [1. 1. 0.]]


In [9]:
a = np.array([1,2,3])
slicing_5 = a[ : : -1]
#Reversed array a array([3, 2, 1]) with jump according to -1 field

print("a: ",a)
print("\na[ : : -1] =\n",slicing_5)

a:  [1 2 3]

a[ : : -1] =
 [3 2 1]


In [10]:
#   Boolean Indexing
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
indexing_1 = a[a<9]
#Select elements from a and return 1D array with the values matches the "if".

print("a: ",a)
print("\na[a<2] =\n",indexing_1)



a:  [[1 2 3]
 [4 5 6]
 [7 8 9]]

a[a<2] =
 [1 2 3 4 5 6 7 8]


In [11]:
#   Fancy Indexing
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
fancy_indexing = b[ [0, 0, 0, 0] , [1, 1, 1, 1] ]
# Select elements [(0,1),(0,1),(0,1),(0,1)] = [2 2 2 2]

print("b: ",b)
print("\nb[[0, 0, 0, 0] , [1, 1, 1, 1]] =\n ",fancy_indexing)

b:  [[1 2 3]
 [4 5 6]
 [7 8 9]]

b[[0, 0, 0, 0] , [1, 1, 1, 1]] =
  [2 2 2 2]


In [12]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
last_indexing = b[ [0, 0, 0, 0] ]   [:,  [2 ,2 ,2 ,2] ]
#Select a subset of the matrix’s rows and columns

print("b: ",b)
print("\nb[ [0, 0, 0, 0] ]   [:,  [2 ,2 ,2 ,2] ] =\n ",last_indexing)

b:  [[1 2 3]
 [4 5 6]
 [7 8 9]]

b[ [0, 0, 0, 0] ]   [:,  [2 ,2 ,2 ,2] ] =
  [[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]
