In [113]:
import numpy as np
print("NumPy Imported")

NumPy Imported


In [114]:
## Transposing Arrayy

b = np.array([[1,2],
              [6,7],
              [11,12]])

i = np.transpose(b,axes=None)
# Changing the axis, (columns transfer into rows and rows transfer into columns)
# axes=None -> Default, axes=(1,0) should be same as len(b.shape), 1->axis 0 go to axis [1], 0->axis 1 go to axis [0].

print("b:\n",b)
print("np.transpose(b,axes=None):\n",i)


b:
 [[ 1  2]
 [ 6  7]
 [11 12]]
np.transpose(b,axes=None):
 [[ 1  6 11]
 [ 2  7 12]]


In [115]:
t = i.T
# Changing the axis, (columns transfer into rows and rows transfer into columns)
# unlike np.transpose(b,axes=None) here there i no hyperparameter called axes.
# always complete transpose of the axis.

print("i:\n",i)
print("i.T:\n",t)

i:
 [[ 1  6 11]
 [ 2  7 12]]
i.T:
 [[ 1  2]
 [ 6  7]
 [11 12]]


In [116]:
## Changing Array Shape
b = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15]])
print("b:\n",b)

ravel = np.ravel(b)
#Flatten the array but unlike np.flatten(b) this function might change the origin
# the Default returned item is like np.view(pointer for origin)

print("np.ravel(b):\n",ravel)
ravel[3] = 1

print("\nravel[3] = 1")
print("b:\n",b)
print("np.ravel(b):\n",ravel)

b:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
np.ravel(b):
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]

ravel[3] = 1
b:
 [[ 1  2  3  1  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
np.ravel(b):
 [ 1  2  3  1  5  6  7  8  9 10 11 12 13 14 15]


In [117]:
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15]])
print("a:\n",a)

resh = np.reshape(a,(-1,1))
#Reshape, this function might change the origin
# the Default returned item is like np.view(pointer for origin).

print("np.reshape(a,(5,3)):\n",resh)

resh[0] = 0
print("resh:\n",resh)
print("a:\n",a)

a:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
np.reshape(a,(5,3)):
 [[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]]
resh:
 [[ 0]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]]
a:
 [[ 0  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [118]:
## Adding/Removing Elements
h = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24])
print("h:\n",h)

resized_h = np.resize(h,(6,4) if len(h)%6==0 and len(h)%4==0 else (1,1))
#Return a new array with shape (2,6)

print("np.resize(h,(6,4) if len(h)%6==0 and len(h)%4==0 else (1,1)):\n",resized_h)
print("h:\n",h)

h:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
np.resize(h,(6,4) if len(h)%6==0 and len(h)%4==0 else (1,1)):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
h:
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [119]:
h = np.array([[1,2,3,4],
              [1,2,3,4]])
g = np.array([[1,2],[3,4]])
new_h = np.append(h,g,axis=1)
# Append items to an array
# while you send with axis = None, 2D array to append for other 2D array
# it will convert to shape(1,) and append the g as 1D array return.
# while send axis = 0, will cause h to return with more indexes. array will append in
# another row according to the value inserted to append.
# (must be same columns never mind the rows.but same dimension)
# with axis = 1/-1 it's will require same indexes shape for both arrays.
# because axis = 1/-1 -> rows usually
#     and axiz = 0 -> columns usually
# Problem: this function is very slow in time production (0(n^2))
# because it is produce a copy of the origin array with all the elements and only after that
# it's append the value.
# Solution: declare list = [] and make instead of np.append
# with lst.append and right after that convert to numpy.ndarray

print("h:\n",h)
print("g:\n",g)
print("np.append(h,g,axis=1):\n",new_h)


h:
 [[1 2 3 4]
 [1 2 3 4]]
g:
 [[1 2]
 [3 4]]
np.append(h,g,axis=1):
 [[1 2 3 4 1 2]
 [1 2 3 4 3 4]]


In [120]:
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10]])
new_a = np.insert(arr=a, obj = [0,0], values= [[0,0],[0,0]], axis = -1)
# Insert items in an array
# obj -> can be used as array of indexes while it is keeping the other params rules.
# obj = [ 0 , 1 ]  -*-> first array in indexes 0 and 1, next array...(values by order)(axis=1)
# obj = [ 0 , 1 ]  -*-> first array in indexes 0 next array in the next obj ,next array...(values by order)(axis=0)
# with axis = 0 values must be same columns as arr, because it's insert row.
# with axis = 1/-1 values must be same rows as arr, because it's insert column.

print("a:\n",a)
print("np.insert(arr=a, obj = [0,0], values= [[0,0],[0,0]], axis = -1):\n",new_a)

a:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
np.insert(arr=a, obj = [0,0], values= [[0,0],[0,0]], axis = -1):
 [[ 0  0  1  2  3  4  5]
 [ 0  0  6  7  8  9 10]]


In [121]:
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10]])

del_a = np.delete(a,0,axis=0)
#Delete items from an array

print("a:\n",a)
print("np.delete(a,0,axis=0):\n",del_a)

a:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
np.delete(a,0,axis=0):
 [[ 6  7  8  9 10]]


In [122]:
## Combining Arrays
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15]])
d = np.array([[1],[2],[5]])

con_arr = np.concatenate((a,d),axis=1)
# Concatenate arrays
#  array([ 1, 2, 3, 10, 15, 20])

print("a:\n",a)
print("d:\n",d)
print("np.concatenate((a,d),axis=1):\n",con_arr)

a:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
d:
 [[1]
 [2]
 [5]]
np.concatenate((a,d),axis=1):
 [[ 1  2  3  4  5  1]
 [ 6  7  8  9 10  2]
 [11 12 13 14 15  5]]


In [123]:
a = np.array([[1,2,3],
              [6,7,8],
              [9,10,11]])

b = np.array([[1,2.5,3.5]],dtype=float)

v_arr = np.vstack((a,b)).astype(int)
# Stack arrays vertically
# as concatenate but axis = 0 is permanent ,
# add rows so the columns must be same.
# a:
#  [[ 1  2  3]
#  [ 6  7  8]
#  [ 9 10 11]]
# b:
#  [[1.  2.5  3.5]]
# np.vstack((a,b),casting='safe'):
#  [[ 1  2  3]
#  [ 6  7  8]
#  [ 9 10 11]
#  [ 1  2  3]]
print("a:\n",a)
print("b:\n",b)
print("np.vstack((a,b)).astype(int):\n",v_arr)

a:
 [[ 1  2  3]
 [ 6  7  8]
 [ 9 10 11]]
b:
 [[1.  2.5 3.5]]
np.vstack((a,b)).astype(int):
 [[ 1  2  3]
 [ 6  7  8]
 [ 9 10 11]
 [ 1  2  3]]


In [124]:
e = np.array([[1,2,3],
              [6,7,8],
              [9,10,11]])
f = np.array([[1], [2.5], [3.5]])
h_arr = np.hstack((e,f))
# Stack arrays horizontally

print("e:\n",e)
print("f:\n",f)
print("np.hstack((e,f)):\n",h_arr)

e:
 [[ 1  2  3]
 [ 6  7  8]
 [ 9 10 11]]
f:
 [[1. ]
 [2.5]
 [3.5]]
np.hstack((e,f)):
 [[ 1.   2.   3.   1. ]
 [ 6.   7.   8.   2.5]
 [ 9.  10.  11.   3.5]]


In [125]:
np.r_[e,f]
#Stack arrays vertically (row-wise)
#same as np.vstack


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 1

In [ ]:
np.c_[a,d]
# Create stacked column-wise arrays
#same as np.hstack


In [ ]:
a = np.array([1, 2, 3])
d = np.array([4, 5, 6])

c_s_arr = np.column_stack((a,d))
# Create stacked column-wise arrays
# convert each column to array in one new matrix.

print("a:\n",a)
print("d:\n",d)
print("np.column_stack((a,d)):\n",c_s_arr)

In [ ]:
## Splitting Arrays
a = np.array([[1, 2, 3],
              [6, 7, 8],
              [9, 10, 11]])
split_h = np.hsplit(a,3)
# Split the array horizontally at the 3rd
#  [array([1]),array([2]),array([3])] index
# by columns.

print("a:\n",a)
print("np.hsplit(a,3):\n",split_h)

In [ ]:
c = np.array([[1, 2, 3],
              [6, 7, 8]])
v_s_arr = np.vsplit(c,2)

# Split the array vertically at the 2nd index
# return as 1D array each value represent the shape of the original shape if c's shape is (2,3)
# that is the type of the returned item in each value in the main 1D array.

print("c:\n",c)
print("np.vsplit(c,2):\n",v_s_arr)